[project]
name = "saga"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "bigfootpp", email = "97189022+Bigfootpp@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "guessit>=4.4.0",
    "httpx>=0.28.1",
    "libtorrent>=2.1.1",
    "loguru>=0.7.3",
    "platformdirs>=4.12.2",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "torf>=4.3.1",
    "uvicorn>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
typeCheckingMode = "standard"
reportMissingModuleSource = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = ["integration: real tests"]
addopts = "-m 'not integration'"

[tool.ruff.lint]
ignore = [
    "S110",
    "BLE001",
    "B017",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "respx>=0.23.1",
    "ruff>=0.16.4",
]
