[project]
name = "saga"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Bigfootpp", email = "97189022+Bigfootpp@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
typeCheckingMode = "standard"
reportMissingModuleSource = false

[tool.pytest.ini_options]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "respx>=0.23.1",
    "ruff>=0.16.4",
]
