[project]
name = "saga"
version = "0.1.0"
description = "A clean, Jackett resolver for Stremio"
readme = "README.md"
authors = [{ name = "Bigfootpp" }]
requires-python = ">=3.12"
dependencies = [
    "bencode-py>=4.1.0",
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "rank-torrent-name>=1.11.1",
    "requests>=2.34.2",
    "starlette>=1.4.1",
    "uvicorn>=0.52.1",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
package = false
