name: code check

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: install deps
        run: uv sync --locked --dev

      - name: basedpyright check
        run: uv run basedpyright

      - name: ruff check
        run: uv run ruff check .
